"use client";
import {useEffect,useState} from "react";
import {api} from "@/lib/api-client";
export function CollaborationPanel({id,version,onChanged}:{id:string;version:string;onChanged:()=>void}){
 const [data,setData]=useState<{comments:{id:string;actor:string;content:string;createdAt:string}[];collaborators:{id:string;name:string;email:string}[];canInvite:boolean}|null>(null),[email,setEmail]=useState(""),[text,setText]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{setData(await api(`/api/documents/${id}/collaboration`));}catch(e){setError((e as Error).message);}}
 useEffect(()=>{void load();},[id,version]);
 async function action(body:unknown){setBusy(true);setError("");try{await api(`/api/documents/${id}/collaboration`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setText("");await load();onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="collaboration-panel"><h3>共同編輯與討論</h3>{data&&<><p>共同編輯者：{data.collaborators.map(m=>m.name).join("、")||"尚未加入其他成員"}</p>{data.canInvite&&<><form onSubmit={e=>{e.preventDefault();void action({action:"invite",email});}}><label>已核准會員的 email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="outline-button" disabled={busy}>加入共同編輯者</button></form>{data.collaborators.map(m=><button className="text-button" key={m.id} disabled={busy} onClick={()=>void action({action:"remove",email:m.email})}>移除 {m.name} 的共筆權限</button>)}</>}<form onSubmit={e=>{e.preventDefault();void action({action:"comment",content:text});}}><label>共筆討論<textarea required maxLength={2000} rows={3} value={text} onChange={e=>setText(e.target.value)} placeholder="留下補充證據、校訂建議或待確認事項"/></label><button className="outline-button" disabled={busy}>送出留言</button></form><button className="primary-button" disabled={busy} onClick={()=>void action({action:"submit",expectedUpdatedAt:version})}>送交教師／地方專家審閱</button><ol className="event-list">{data.comments.map(c=><li key={c.id}><small>{c.actor} · {new Date(c.createdAt).toLocaleString("zh-TW")}</small><p className="preserve-lines">{c.content}</p></li>)}</ol></>}{error&&<p role="alert" className="error-message">{error}</p>}</section>;
}
