"use client";
import { useState } from "react";
import { ArrowUpRight, BookOpen, Download, Image, MapPin, MessageSquareText, ShieldCheck, Wrench } from "lucide-react";
import type { KnowledgeDocument } from "@/lib/knowledge";
import { topics, exportText } from "@/lib/community-content";
import { DemoImage, DemoReadingGuide } from "./demo-image";
import { canRead } from "@/lib/governance";
import { MAIN_SITE } from "@/lib/site-runtime";

export type HubView = "wiki" | "journal" | "lab" | "tools" | "governance";
export const hubTitles: Record<HubView,string> = {wiki:"地方主題百科", journal:"地方影像誌", lab:"雙向共學實驗室", tools:"教學與田野工具箱", governance:"文化治理"};
const icons = {wiki:BookOpen,journal:Image,lab:MessageSquareText,tools:Wrench,governance:ShieldCheck};
export function Portal({go}: {go:(v:HubView)=>void}) {
  return <section className="hub-portal" aria-label="地方共學入口"><div><span className="eyebrow">LEARN WITH THE COMMUNITY</span><h2>從紀錄，走向地方共學</h2><p>理解知識的來處，也一起決定它的去向。</p></div><div className="portal-links">{(Object.keys(hubTitles) as HubView[]).map(v=>{const Icon=icons[v];return <button key={v} onClick={()=>go(v)}><Icon size={22}/><span>{hubTitles[v]}</span><ArrowUpRight size={16}/></button>;})}</div></section>;
}
export function CommunityHub({view,documents,open,ask,go,editor,publicPages}: {view:HubView;documents:KnowledgeDocument[];open:(id:string)=>void;ask:(question:string)=>void;go:(v:HubView)=>void;editor:boolean;publicPages:boolean}) {
  const [filter,setFilter]=useState(""),[chosen,setChosen]=useState<string>("coast"),[region,setRegion]=useState("");
  const visible=documents.filter(canRead);
  const selected=topics.find(t=>t.id===chosen)??topics[0];
  const related=visible.filter(d=>selected.keys.some(k=>(d.title+d.summary+d.tags.join(" ")).includes(k)));
  return <><div className="page-heading"><div><div className="eyebrow">COMMUNITY · KNOWLEDGE · CARE</div><h1>{hubTitles[view]}</h1><p>{{wiki:"以主題串起教學與田野，保留來源、語境與不同觀點。",journal:"從影像進入地方；每一張圖都要能說明來源與用途。",lab:"把社群經驗與研究證據並置，共同形成下一步行動。",tools:"在裝置上整理可審閱、可帶回課堂的工作文件。",governance:"讓文化持有者參與命名、審閱、公開與撤回的決定。"}[view]}</p></div></div>
  {view==="wiki"&&<><div className="hub-toolbar"><label>搜尋主題<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="海岸、語言、文化治理…"/></label></div><div className="topic-layout"><div className="topic-index" role="group" aria-label="百科主題">{topics.filter(t=>(t.title+t.text+t.region).includes(filter.trim())).map(t=><button className={chosen===t.id?"selected":""} key={t.id} onClick={()=>setChosen(t.id)}><small>{t.region}</small><strong>{t.title}</strong></button>)}</div><article className="hub-card topic-detail"><span className="pill">編輯導讀 · 非田野事實</span><h2>{selected.title}</h2><p>{selected.text}</p><h3>帶著問題閱讀</h3><ul>{selected.questions.map(q=><li key={q}>{q}</li>)}</ul><h3>相關知識紀錄 · {related.length}</h3><div className="related-list">{related.map(d=><button key={d.id} onClick={()=>open(d.id)}><span>{d.isDemo?"示範":"成果"} · {d.region}</span><strong>{d.title}</strong><ArrowUpRight size={17}/></button>)}{!related.length&&<p>目前尚無相關公開成果。</p>}</div><button className="outline-button" onClick={()=>ask(selected.keys[0]+"的知識如何記錄與傳承")}><MessageSquareText size={17}/>向相關紀錄提問</button></article></div></>}
  {view==="journal"&&<><div className="collection-note"><Image size={22}/><p><strong>六張 AI 示意插畫。</strong>圖片連結至示範原文；不是現場照片，也不會作為 RAG 的事實證據。真實影音附件由主系統保存，目前不自動辨識或轉錄。</p></div><div className="region-tabs" role="group" aria-label="影像區域">{["","新屋","楊梅","平鎮","跨區"].map(r=><button key={r} className={region===r?"selected":""} onClick={()=>setRegion(r)}>{r||"全部地方"}</button>)}</div><div className="journal-grid">{visible.filter(d=>d.isDemo&&(!region||d.region===region)).map(d=><article className="hub-card journal-card" key={d.id}><DemoImage id={d.id} isDemo detail/><div className="journal-copy"><span className="pill">{d.region} · {d.category}</span><h2>{d.title}</h2><p>{d.summary}</p><DemoReadingGuide id={d.id} isDemo/><dl><dt>影像來源</dt><dd>本系統原創 AI 示意插畫</dd><dt>使用目的</dt><dd>教學導讀；引用原文依該成果授權</dd></dl><button className="outline-button" onClick={()=>open(d.id)}>閱讀原文與授權</button></div></article>)}</div>{!visible.some(d=>d.isDemo)&&<div className="empty-state">目前沒有可公開展示的示範影像。</div>}</>}
  {view==="lab"&&<Lab/>}
  {view==="tools"&&<Tools documents={visible} open={open} ask={ask}/>}
  {view==="governance"&&<GovernanceGuide editor={editor} publicPages={publicPages} go={go}/>}
  </>;
}
function Lab(){
 const [values,setValues]=useState({topic:"",community:"",research:"",difference:"",action:""});
 const labels={topic:"共學議題與參與者",community:"社群經驗與原來的語境",research:"研究／文獻證據及來源",difference:"差異、未知與不可公開事項",action:"共同決定、回饋方式及再訪日期"};
 return <><div className="lab-intro"><span className="pill">在地共學方法</span><h2>並置觀點，留下差異</h2><p>邀請居民、文化持有者、教師與學員對話。經驗與研究各自保留來源；對不上時先記錄差異，再約定如何查證與回饋。</p><small>參考原傳媒的雙向知識入口。Two-Eyed Seeing 源於 Mi’kmaq 知識脈絡；此處為在地共學工作表，不宣稱代表任何族群的方法或知識。<a href="https://yuan-media-ai.vercel.app/two-eyed-seeing" target="_blank" rel="noreferrer">閱讀參考</a></small></div><form className="hub-card worksheet" onSubmit={e=>{e.preventDefault();exportText("新楊平-雙向共學工作表.md","# 雙向共學工作表\n\n"+Object.entries(labels).map(([k,label])=>`## ${label}\n${values[k as keyof typeof values]}\n`).join("\n")+"\n本工作表由使用者填寫，非 AI 生成；發布前須取得參與者同意。\n");}}><h2>開始一份共學工作表</h2><p>內容只保留在目前頁面，下載後可帶回課堂；重新整理會清空。請勿在未取得同意時填入個資。</p><div className="dialogue-grid">{Object.entries(labels).map(([k,label])=><label key={k} className={k==="topic"||k==="action"?"full-width":""}>{label}<textarea required value={values[k as keyof typeof values]} onChange={e=>setValues({...values,[k]:e.target.value})} rows={k==="topic"?2:5} maxLength={3000} placeholder={k==="research"?"作者／機構、日期、頁碼或網址；證據能支持的範圍":"請填寫實際討論內容，尚未確認請明確註記。"}/></label>)}</div><button className="primary-button" type="submit"><Download size={18}/>下載共學工作表</button></form></>;
}
function Tools({documents,open,ask}:{documents:KnowledgeDocument[];open:(id:string)=>void;ask:(q:string)=>void}){
 const [kind,setKind]=useState("走讀教案"),[id,setId]=useState(""),[purpose,setPurpose]=useState(""),[draft,setDraft]=useState("");
 function make(){const d=documents.find(d=>d.id===id); if(!d)return;const source=`${d.title}｜${d.author}｜${d.recordedAt||"未註記日期"}\n授權：${d.license}\n${d.sourceUrl||location.origin+location.pathname+"?document="+encodeURIComponent(d.id)}`; const sections=kind==="走讀教案"?["學習目標（教師補充）","觀察路線與安全規畫（教師補充）","比較在地經驗與文獻","討論與回饋"]:kind==="訪談提綱"?["訪談同意與公開範圍","生活經驗與用語","不同說法與待查證事項","受訪者回看、撤回聯繫與再訪"]:["本期閱讀焦點","原文摘錄與來源核對","社群回饋（待填）","下次共學與參與方式（待填）"];setDraft(`# ${kind}草稿\n\n用途：${purpose}\n\n## 閱讀材料\n${source}\n\n## 已發布摘要\n${d.summary}\n\n${sections.map(s=>`## ${s}\n[請依現場與來源填寫]\n`).join("\n")}\n${d.isDemo?"【示範材料，非正式田野成果】\n":""}本文件以固定模板整理，未使用 AI 生成。請核對來源並由參與社群與教師審閱後使用。`);}
 return <><div className="tool-shortcuts"><button className="hub-card" onClick={()=>ask("如何保存長輩的故事")}><MessageSquareText/><h2>有來源的語意問答</h2><p>使用現有 RAG 找段落，回到完整原文核對。</p></button><div className="hub-card"><MapPin/><h2>地方地景入口</h2><p>以行政區名稱開啟地圖，不提供敏感文化地點座標。</p><div className="tags">{["新屋","楊梅","平鎮"].map(r=><a key={r} href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent("桃園市"+r+"區")}`} target="_blank" rel="noreferrer">{r} ↗</a>)}</div></div></div><section className="hub-card worksheet"><span className="pill">文件模板 · 裝置內處理</span><h2>把閱讀材料帶回課堂</h2><p>選擇公開紀錄，產出可編輯的教案、訪談提綱或共學電子報草稿。這是模板工具，不會捏造新的事實，也不會寄送電子報。</p><div className="form-grid"><label>文件類型<select value={kind} onChange={e=>{setKind(e.target.value);setDraft("");}}>{["走讀教案","訪談提綱","共學電子報"].map(k=><option key={k}>{k}</option>)}</select></label><label>閱讀來源<select value={id} onChange={e=>{setId(e.target.value);setDraft("");}}><option value="">請選擇紀錄</option>{documents.map(d=><option key={d.id} value={d.id}>{d.isDemo?"示範 · ":""}{d.title}</option>)}</select></label><label className="full-width">對象與使用目的<input maxLength={300} value={purpose} onChange={e=>{setPurpose(e.target.value);setDraft("");}} placeholder="例如：成人走讀課程，討論海岸技藝的傳承"/></label></div><div className="form-actions"><button className="primary-button" disabled={!id||!purpose.trim()} onClick={make}><Wrench size={18}/>建立文件草稿</button>{id&&<button className="outline-button" onClick={()=>open(id)}>核對來源原文</button>}</div>{draft&&<div className="draft-output"><label>審閱與修改<textarea aria-label="文件草稿" value={draft} onChange={e=>setDraft(e.target.value)} rows={18} maxLength={15000}/></label><button className="outline-button" onClick={()=>exportText(`新楊平-${kind}.md`,draft)}><Download size={18}/>下載 Markdown</button></div>}</section></>;
}
function GovernanceGuide({editor,publicPages,go}:{editor:boolean;publicPages:boolean;go:(v:HubView)=>void}){
 const steps=[{title:"共同決定要記錄什麼",text:"課程開始前與居民、文化持有者討論目的、名稱、記錄方法及不記錄的範圍；不以一位受訪者代表整個地方。"},{title:"分開確認各種使用",text:"同意保存、同意公開、AI 檢索及再利用分開協商。照片、聲音與文字的範圍可能不同；表單不是同意本身的替代品。"},{title:"社群回看與審閱",text:"提供原文、翻譯與影像供參與者回看。填寫文化持有社群、脈絡、使用邊界與審閱依據，保留不同說法；需要時可限制為編輯保存。"},{title:"發布、回饋與持續協商",text:"審閱完成的公開版本才能瀏覽；另有 AI 許可才開放檢索。讓成果回到地方課堂、共學活動與參與者，定期確認用途仍符合原約定。"},{title:"撤回與版本留痕",text:"社群可向課程教師或知識庫管理員提出更正與撤回。編輯撤回後原文、附件與檢索立即不再對讀者提供；修訂後重新審閱。"}];
 return <><div className="governance-banner"><ShieldCheck size={38}/><div><h2>保存不等於公開；公開需另外確認 AI 使用</h2><p>文化持有者的決定，應在資料表、檢索和教學現場都能被執行。</p></div></div><div className="governance-steps">{steps.map((s,i)=><article className="hub-card" key={s.title}><span className="step-number">0{i+1}</span><div><h2>{s.title}</h2><p>{s.text}</p></div></article>)}</div><div className="dialogue-grid"><article className="hub-card"><h2>一起治理的人</h2><p>文化持有者與受訪者決定文化邊界；教師／田野團隊整理來源與回饋；社群審閱者核對詮釋；知識庫編輯依協議執行發布與撤回。</p><p>目前系統使用共用編輯金鑰，角色是協作分工，尚未具備個別帳號或獨立多人簽核。</p><button className="outline-button" onClick={()=>go("lab")}>開啟共學工作表</button></article><article className="hub-card"><h2>授權與技術邊界</h2><p>授權條款不會自動涵蓋所有人物、場所或文化知識。公開版本的截圖、既有下載或外部引用無法由系統遠端收回，需與使用者協商處理。</p><p>審閱理由與修訂前快照僅供編輯存取；永久刪除成果會連同版本紀錄刪除。請依社群約定辦理保留與刪除。</p><a href="https://ich.unesco.org/en/drawing-up-inventories-00313" target="_blank" rel="noreferrer">參考：UNESCO 社群參與與文化清冊</a></article></div><section className="hub-card governance-entry"><h2>成果審閱與撤回</h2><p>{publicPages?"GitHub 展示版只有公開示範；正式資料的權限與修訂紀錄保存在主系統。":editor?"請從「探索知識 → 管理成果與草稿」開啟正式紀錄，在原文頁底部審閱、設定權限或撤回。":"請由教師或管理員在主系統登入，開啟成果原文進行審閱與撤回。"}</p><a className="outline-button" href={MAIN_SITE} target="_blank" rel="noreferrer">前往主系統</a></section></>;
}
