"use client";
import { useEffect, useState, type FormEvent } from "react";
import { api } from "@/lib/api-client";
import type { KnowledgeDocument } from "@/lib/knowledge";
import { exportText } from "@/lib/community-content";
type Event = {id:string;action:string;actor:string;reason:string;snapshot:string;createdAt:string};
export function GovernancePanel({document:d,editor,reviewer,onChanged}:{document:KnowledgeDocument;editor:boolean;reviewer:boolean;onChanged:()=>void}){
 const g=d.governance;
 const [community,setCommunity]=useState(g?.community??""),[context,setContext]=useState(g?.culturalContext??""),[access,setAccess]=useState(g?.accessLevel??"editor"),[ai,setAi]=useState(g?.aiAllowed??false),[note,setNote]=useState(""),[events,setEvents]=useState<Event[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{if(editor&&!d.isDemo)void api<{events:Event[]}>(`/api/documents/${d.id}/governance`).then(r=>setEvents(r.events)).catch(e=>setError(e.message));},[d.id,d.updatedAt,editor,d.isDemo]);
 async function decide(action:"review"|"withdraw"){
  setBusy(true);setError("");try{await api(`/api/documents/${d.id}/governance`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,expectedUpdatedAt:d.updatedAt,community,culturalContext:context,accessLevel:access,aiAllowed:ai,reviewNote:note})});onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 return <section className="record-governance"><h3>文化脈絡與使用邊界</h3><div className="tags"><span>{d.isDemo?"示範素材":g?.reviewState==="approved"?"已審閱":g?.reviewState==="withdrawn"?"已撤回":"待審閱"}</span><span>{g?.accessLevel==="public"?"公開閱讀":"僅編輯保存"}</span><span>{g?.aiAllowed?"允許 AI 檢索":"不供 AI 檢索"}</span></div><p><strong>文化持有社群：</strong>{g?.community||"待補充"}</p><p className="preserve-lines">{g?.culturalContext||"待與社群確認脈絡及使用限制。"}</p>
 {editor&&!d.isDemo&&<>{reviewer&&<form onSubmit={(e:FormEvent)=>{e.preventDefault();void decide("review");}}><h3>社群審閱決定</h3><p>請先與參與者確認實際同意及審閱結果，再由編輯登錄。系統會記錄執行審閱的個別會員署名。</p><div className="form-grid"><label className="full-width">文化持有社群／參與者範圍<input required minLength={2} maxLength={200} value={community} onChange={e=>setCommunity(e.target.value)}/></label><label className="full-width">文化脈絡與使用邊界（公開版可見，請勿填入秘密或個資）<textarea required minLength={10} maxLength={1000} rows={3} value={context} onChange={e=>setContext(e.target.value)}/></label><label>公開範圍<select value={access} onChange={e=>setAccess(e.target.value as "public"|"editor")}><option value="editor">僅編輯保存</option><option value="public">審閱後公開閱讀</option></select></label><label className="consent-label"><input type="checkbox" checked={ai} disabled={access!=="public"} onChange={e=>setAi(e.target.checked)}/>已另行確認允許 AI 檢索與整理回答</label><label className="full-width">審閱／撤回依據（限編輯可見）<textarea required minLength={10} maxLength={1500} rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="審閱者、日期、確認方式、允許用途與再確認期限；撤回時填寫提出者及處理理由。"/></label></div>{!d.consent&&<p className="demo-warning">尚未確認同意，請先編輯成果並確認授權後再審閱。</p>}<div className="form-actions"><button className="primary-button" disabled={busy||!d.consent} type="submit">儲存審閱決定</button><button className="danger-button" type="button" disabled={busy||note.trim().length<10} onClick={()=>void decide("withdraw")}>撤回公開與檢索</button></div></form>}{error&&<p role="alert" className="error-message">{error}</p>}<h3>修訂與治理紀錄</h3><ol className="event-list">{events.map(e=><li key={e.id}><strong>{{created:"建立草稿",revised:"修訂原文",reviewed:"審閱決定",withdrawn:"撤回"}[e.action]||e.action}</strong><small>{new Date(e.createdAt).toLocaleString("zh-TW")} · {e.actor}</small><p>{e.reason}</p><button className="text-button" onClick={()=>exportText(`成果版本-${d.id}-${e.id}.json`,JSON.stringify(JSON.parse(e.snapshot),null,2),"application/json;charset=utf-8")}>下載此筆版本快照（含原文）</button></li>)}</ol></>}
 </section>;
}
