"use client";
import { useState, type ReactNode } from "react";
import { LIBRARIES,libraryById } from "@/lib/libraries";
import { batchRecord,parseCSV } from "@/lib/batch-import";
import { REGIONS } from "@/lib/knowledge";
import { api } from "@/lib/api-client";
import { exportText } from "@/lib/community-content";
import { MAIN_SITE,isPublicPages } from "@/lib/site-runtime";
export function KnowledgeWorkbench({editingLibrary,allowed,children,onLibrary,onSaved}:{editingLibrary?:string;allowed:boolean;children:(library:string)=>ReactNode;onLibrary?:()=>void;onSaved:()=>void}){
 const [library,setLibrary]=useState(editingLibrary??"ecology"),[mode,setMode]=useState("single");const spec=libraryById(library);
 return <section className="knowledge-workbench"><div className="workbench-intro"><span className="eyebrow">SIX LOCAL KNOWLEDGE LIBRARIES</span><h2>六大庫共筆工作室</h2><p>依張陳基院長簡報第 26–34 頁，讓每一門課留下可追溯、可接續的地方知識。</p></div><div className="library-picker" role="group" aria-label="選擇知識庫">{LIBRARIES.map((l,i)=><button key={l.id} className={library===l.id?"library-choice selected":"library-choice"} onClick={()=>{setLibrary(l.id);onLibrary?.();}} disabled={!!editingLibrary&&l.id!==editingLibrary}><span>0{i+1} · {l.layout}</span><strong>{l.name}</strong><small>{l.description}</small></button>)}</div><div className="workbench-toolbar"><div><h3>{spec.name} · {spec.layout}</h3><p>{mode==="batch"?"先預覽與核對，再整批保存草稿。":"專屬欄位與原文一起保存，修訂留有版本。"}</p></div><div className="mode-switch"><button className={mode==="single"?"active":""} onClick={()=>setMode("single")}>單筆編輯</button><button disabled={!!editingLibrary} className={mode==="batch"?"active":""} onClick={()=>setMode("batch")}>批次上傳</button></div></div>{LIBRARIES.map(l=><div key={l.id} hidden={mode!=="single"||library!==l.id}>{(!editingLibrary||editingLibrary===l.id)&&children(l.id)}</div>)}<div hidden={mode!=="batch"}><BatchEditor key={library} library={library} allowed={allowed} onSaved={onSaved}/></div></section>;
}
function BatchEditor({library,allowed,onSaved}:{library:string;allowed:boolean;onSaved:()=>void}){
 const [author,setAuthor]=useState(""),[course,setCourse]=useState(""),[region,setRegion]=useState("新屋"),[preview,setPreview]=useState(""),[files,setFiles]=useState<File[]>([]),[requestId,setRequestId]=useState(crypto.randomUUID()),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[uploaded,setUploaded]=useState<string[]>([]),[receipt,setReceipt]=useState<string[]>([]);const spec=libraryById(library);
 let rows:Record<string,unknown>[]=[];try{const value=JSON.parse(preview);if(Array.isArray(value))rows=value;}catch{}
 function changeRow(i:number,key:string,value:unknown){const next=[...rows];next[i]={...next[i],[key]:value};setPreview(JSON.stringify(next,null,2));setRequestId(crypto.randomUUID());}
 function template(format:string){const record={title:"請填寫成果標題",summary:"請填寫至少十字的內容摘要",content:"請填寫至少三十字的原文與資料來源，不要將範本當成正式成果。",author:"",course:"",region:"新屋",recordedAt:"",sourceUrl:"",consent:false,...Object.fromEntries(spec.fields.map(k=>[k,""]))};if(format==="json")exportText(`${spec.name}-匯入範本.json`,JSON.stringify([record],null,2),"application/json;charset=utf-8");else{const quote=(v:unknown)=>`"${String(v).replaceAll('"','""')}"`;exportText(`${spec.name}-匯入範本.csv`,"\uFEFF"+Object.keys(record).map(quote).join(",")+"\r\n"+Object.values(record).map(quote).join(","),"text/csv;charset=utf-8");}}
 async function importFiles(list:File[]){setBusy(true);setMessage("");setReceipt([]);setUploaded([]);setRequestId(crypto.randomUUID());try{if(!list.length||list.length>30)throw new Error("一次請選擇 1–30 個檔案。");if(list.some(f=>f.size>10485760)||list.reduce((n,f)=>n+f.size,0)>30*1048576)throw new Error("每檔上限 10 MB，整批上限 30 MB。");const structured=list.some(f=>/\.(json|csv)$/i.test(f.name));let records:Record<string,unknown>[];if(structured){if(list.length!==1)throw new Error("CSV／JSON 每批請選擇一個檔案。");if(list[0].size>900000)throw new Error("CSV／JSON 檔案請小於 900 KB。");const text=await list[0].text();const rows=/\.csv$/i.test(list[0].name)?parseCSV(text):JSON.parse(text);if(!Array.isArray(rows)||!rows.length||rows.length>30||rows.some(v=>!v||typeof v!=="object"||Array.isArray(v)))throw new Error("CSV／JSON 必須包含 1–30 筆資料。");records=rows;setFiles([]);}else{const {importText}=await import("@/lib/import-file");records=[];for(const f of list){const content=await importText(f);records.push({title:f.name.replace(/\.[^.]+$/,""),content,summary:content.slice(0,180)});}setFiles(list);}setPreview(JSON.stringify(records.map(v=>batchRecord(v,library,author,course,region)),null,2));}catch(e){setMessage((e as Error).message);setPreview("");}finally{setBusy(false);}}
 async function save(){setBusy(true);setMessage("");try{const records=JSON.parse(preview);if(!Array.isArray(records))throw new Error("預覽需為 JSON 陣列。");if(records.some(r=>r.library!==library))throw new Error("這批資料的知識庫需與目前選擇一致。");const result=await api<{documents:{id:string}[]}>("/api/documents/batch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId,records})});setReceipt(result.documents.map(d=>d.id));const done=[...uploaded];for(let i=0;i<files.length;i++){const id=result.documents[i].id;if(done.includes(id))continue;const body=new FormData();body.append("file",files[i]);await api(`/api/documents/${id}/attachments`,{method:"POST",body});done.push(id);setUploaded([...done]);}setMessage(`已保存 ${result.documents.length} 筆草稿${files.length?`與 ${files.length} 個原始附件`:""}。請逐筆核對並送審。`);onSaved();}catch(e){setMessage(`匯入未全部完成：${(e as Error).message} 若原文已保存，重試同一批次不會重複建立成果。`);}finally{setBusy(false);}}
 return <div className="contribution-form"><h3>批次匯入 {spec.name}</h3><p>支援 CSV／JSON 清單，或多個 TXT、MD、含文字 PDF。所有資料先存為草稿，授權預設未確認；AI 索引需取得同意後逐筆建立。</p><div className="form-grid"><label>預設記錄者<input value={author} onChange={e=>setAuthor(e.target.value)} maxLength={100}/></label><label>課程／計畫<input value={course} onChange={e=>setCourse(e.target.value)} maxLength={150}/></label><label>預設地方<select value={region} onChange={e=>setRegion(e.target.value)}>{REGIONS.map(r=><option key={r}>{r}</option>)}</select></label></div><div className="form-actions"><button type="button" className="outline-button" onClick={()=>template("csv")}>下載 CSV 範本</button><button type="button" className="outline-button" onClick={()=>template("json")}>下載 JSON 範本</button></div><label className="batch-upload">選擇批次檔案<input disabled={busy} multiple type="file" accept=".csv,.json,.txt,.md,.pdf" onChange={e=>void importFiles(Array.from(e.target.files??[]))}/></label>{preview&&<><h3>逐筆預覽與核對 · {rows.length} 筆</h3>{rows.map((r,i)=><details className="batch-record" key={i} open={i===0}><summary>第 {i+1} 筆 · {String(r.title??"未命名")}</summary><div className="form-grid"><label>成果標題<input value={String(r.title??"")} maxLength={150} disabled={busy||receipt.length>0} onChange={e=>changeRow(i,"title",e.target.value)}/></label><label>記錄者<input value={String(r.author??"")} maxLength={100} disabled={busy||receipt.length>0} onChange={e=>changeRow(i,"author",e.target.value)}/></label><label className="full-width">摘要<textarea rows={2} value={String(r.summary??"")} maxLength={500} disabled={busy||receipt.length>0} onChange={e=>changeRow(i,"summary",e.target.value)}/></label><label className="full-width">原文（至少 30 字）<textarea rows={5} value={String(r.content??"")} maxLength={20000} disabled={busy||receipt.length>0} onChange={e=>changeRow(i,"content",e.target.value)}/></label><label>地方<select value={String(r.region??"新屋")} disabled={busy||receipt.length>0} onChange={e=>changeRow(i,"region",e.target.value)}>{REGIONS.map(v=><option key={v}>{v}</option>)}</select></label><label>課程／計畫<input value={String(r.course??"")} disabled={busy||receipt.length>0} onChange={e=>changeRow(i,"course",e.target.value)}/></label></div></details>)}<details><summary>進階欄位預覽與修正</summary><label>匯入預覽（可修正欄位；每筆至少 30 字原文）<textarea aria-label="批次匯入預覽" value={preview} disabled={busy||receipt.length>0} rows={14} onChange={e=>{setPreview(e.target.value);setRequestId(crypto.randomUUID());}}/></label></details><p>同一批次會整批驗證；格式錯誤時不建立任何草稿。多個文字檔的原始附件另行上傳。</p>{allowed?<button className="primary-button" disabled={busy||(!files.length&&receipt.length>0)} onClick={()=>void save()}>{busy?"正在匯入…":receipt.length?"重試未完成附件":"確認並整批保存草稿"}</button>:<p className="demo-warning">{isPublicPages()?<a href={MAIN_SITE}>前往主系統登入後保存</a>:"請先申請會員並取得管理員核准，才能保存。"}</p>}</>}{message&&<p role="status" className="form-policy">{message}</p>}{receipt.length>0&&<ul>{receipt.map((id,i)=><li key={id}><a href={`?document=${id}`}>第 {i+1} 筆已保存的草稿</a></li>)}</ul>}</div>;
}
