"use client";
import {useEffect,useState} from "react";
import {api} from "@/lib/api-client";
import {isPublicPages,MAIN_SITE} from "@/lib/site-runtime";
type Member={id:string;email:string;name:string;role:string;state:string};
export function MemberCenter({onChanged}:{onChanged:()=>void}){
 const [data,setData]=useState<{member:Member|null;identity:boolean;admin:boolean;members:Member[]}|null>(null),[name,setName]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){try{setData(await api("/api/members"));}catch(e){setError((e as Error).message);}}
 useEffect(()=>{if(!isPublicPages())void load();},[]);
 async function mutate(method:string,body:unknown){setBusy(true);setError("");try{await api("/api/members",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});await load();onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="member-center"><div className="page-heading"><div><span className="eyebrow">COMMUNITY MEMBERSHIP</span><h1>會員與共筆</h1><p>使用個人帳號申請；管理員核准後，老師可建立成果並邀請已核准的會員共同編輯。</p></div></div><div className="membership-steps"><span>01 帳號登入</span><span>02 申請會員</span><span>03 管理員核准</span><span>04 六大庫共筆</span></div>{isPublicPages()?<div className="editor-gate"><h2>在主系統使用個人會員帳號</h2><p>GitHub Pages 提供六大庫版面與批次範本預覽。會員、原始附件與共筆紀錄保存在主系統。</p><a className="primary-button" href={MAIN_SITE+"?view=members"} target="_blank" rel="noopener noreferrer">前往主系統申請會員</a></div>:data&&!data.identity&&!data.admin?<div className="editor-gate"><h2>登入您的 ChatGPT 帳號</h2><a className="primary-button" href="/signin-with-chatgpt?return_to=%2F%3Fview%3Dmembers" target="_top">會員登入</a></div>:data&&<div className="contribution-form"><h2>{data.member?`${data.member.name}，您好`:"申請加入新楊平共筆"}</h2>{data.member&&<p>會員狀態：{{pending:"等待管理員核准",active:"已核准",suspended:"已停用"}[data.member.state]??data.member.state} · 角色：{{teacher:"教師／共同編輯者",reviewer:"教師／地方專家審閱者",admin:"管理員"}[data.member.role]}</p>}{data.identity&&<form onSubmit={e=>{e.preventDefault();void mutate("POST",{name});}}><label>姓名／共筆署名<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder={data.member?.name??"請填寫您的姓名"}/></label><button className="primary-button" disabled={busy} type="submit">{data.member?"更新署名":"送出會員申請"}</button></form>}{data.admin&&<><h3>會員核准與角色管理</h3><p>教師只能編輯自己建立或受邀的成果；審閱者可查核全部草稿。停用後即失去共筆權限。</p><div className="member-list">{data.members.map(m=><div className="member-row" key={m.id}><div><strong>{m.name}</strong><small>{m.email} · {m.state}</small></div>{m.role==="admin"?<span>管理員</span>:<><select aria-label={`${m.name}的角色`} value={m.role} disabled={busy} onChange={e=>void mutate("PATCH",{id:m.id,role:e.target.value,state:m.state==="active"?"active":"suspended"})}><option value="teacher">教師／共筆</option><option value="reviewer">審閱者</option></select><button className="outline-button" disabled={busy} onClick={()=>void mutate("PATCH",{id:m.id,role:m.role,state:m.state==="active"?"suspended":"active"})}>{m.state==="active"?"停用":"核准"}</button></>}</div>)}</div></>}{data.identity&&<a className="text-button" href="/signout-with-chatgpt?return_to=%2F" target="_top">登出會員帳號</a>}</div>}{error&&<p role="alert" className="error-message">{error}</p>}<div className="form-policy"><strong>共筆與文化治理</strong><p>每次保存會記錄會員署名與版本。多人同時修改時，系統會阻擋覆蓋較新的版本，請重新載入後整合。共同編輯者可留言討論、送審；公開閱讀與 AI 檢索仍須經審閱及同意確認。</p></div></section>;
}
